### ISSUE TITLE
Нанести остановку "Зеленый рынок" на OSM

### ISSUE THREAD

**Issue by serjvanilla** [MagnitogorskTrams/v0#1]
Где-то тут http://www.openstreetmap.org/#map=19/53.43459/58.96168

**Comment by az09** [comment]
Значит про дефолтное значение игнорируешь?.. Так и будут новые остановки в океан сваливаться

**Comment by serjvanilla** [comment]
А про дефолтное значение надо бы ишью отдельный вообще-то
Но уже пофиксил

**Comment by az09** [comment]
http://www.openstreetmap.org/browse/node/370062231
